// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: grpc.proto

package grpcpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AntiBruteforceClient is the client API for AntiBruteforce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AntiBruteforceClient interface {
	// Search returns a Google search result for the query.
	AccessRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
	ClearBucket(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
	AddToWhileList(ctx context.Context, in *SubNet, opts ...grpc.CallOption) (*Result, error)
	DelFromWhileList(ctx context.Context, in *SubNet, opts ...grpc.CallOption) (*Result, error)
	AddToBlackList(ctx context.Context, in *SubNet, opts ...grpc.CallOption) (*Result, error)
	DelFromBlackList(ctx context.Context, in *SubNet, opts ...grpc.CallOption) (*Result, error)
}

type antiBruteforceClient struct {
	cc grpc.ClientConnInterface
}

func NewAntiBruteforceClient(cc grpc.ClientConnInterface) AntiBruteforceClient {
	return &antiBruteforceClient{cc}
}

func (c *antiBruteforceClient) AccessRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ab_grpc.anti_bruteforce/AccessRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) ClearBucket(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ab_grpc.anti_bruteforce/clearBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) AddToWhileList(ctx context.Context, in *SubNet, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ab_grpc.anti_bruteforce/AddToWhileList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) DelFromWhileList(ctx context.Context, in *SubNet, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ab_grpc.anti_bruteforce/DelFromWhileList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) AddToBlackList(ctx context.Context, in *SubNet, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ab_grpc.anti_bruteforce/AddToBlackList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) DelFromBlackList(ctx context.Context, in *SubNet, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ab_grpc.anti_bruteforce/DelFromBlackList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AntiBruteforceServer is the anti-bruteforce API for AntiBruteforce service.
// All implementations must embed UnimplementedAntiBruteforceServer
// for forward compatibility
type AntiBruteforceServer interface {
	// Search returns a Google search result for the query.
	AccessRequest(context.Context, *Request) (*Result, error)
	ClearBucket(context.Context, *Request) (*Result, error)
	AddToWhileList(context.Context, *SubNet) (*Result, error)
	DelFromWhileList(context.Context, *SubNet) (*Result, error)
	AddToBlackList(context.Context, *SubNet) (*Result, error)
	DelFromBlackList(context.Context, *SubNet) (*Result, error)
	mustEmbedUnimplementedAntiBruteforceServer()
}

// UnimplementedAntiBruteforceServer must be embedded to have forward compatible implementations.
type UnimplementedAntiBruteforceServer struct {
}

func (UnimplementedAntiBruteforceServer) AccessRequest(context.Context, *Request) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccessRequest not implemented")
}
func (UnimplementedAntiBruteforceServer) ClearBucket(context.Context, *Request) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearBucket not implemented")
}
func (UnimplementedAntiBruteforceServer) AddToWhileList(context.Context, *SubNet) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToWhileList not implemented")
}
func (UnimplementedAntiBruteforceServer) DelFromWhileList(context.Context, *SubNet) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelFromWhileList not implemented")
}
func (UnimplementedAntiBruteforceServer) AddToBlackList(context.Context, *SubNet) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToBlackList not implemented")
}
func (UnimplementedAntiBruteforceServer) DelFromBlackList(context.Context, *SubNet) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelFromBlackList not implemented")
}
func (UnimplementedAntiBruteforceServer) mustEmbedUnimplementedAntiBruteforceServer() {}

// UnsafeAntiBruteforceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AntiBruteforceServer will
// result in compilation errors.
type UnsafeAntiBruteforceServer interface {
	mustEmbedUnimplementedAntiBruteforceServer()
}

func RegisterAntiBruteforceServer(s grpc.ServiceRegistrar, srv AntiBruteforceServer) {
	s.RegisterService(&AntiBruteforce_ServiceDesc, srv)
}

func _AntiBruteforce_AccessRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).AccessRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ab_grpc.anti_bruteforce/AccessRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).AccessRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_ClearBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).ClearBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ab_grpc.anti_bruteforce/clearBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).ClearBucket(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_AddToWhileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubNet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).AddToWhileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ab_grpc.anti_bruteforce/AddToWhileList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).AddToWhileList(ctx, req.(*SubNet))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_DelFromWhileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubNet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).DelFromWhileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ab_grpc.anti_bruteforce/DelFromWhileList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).DelFromWhileList(ctx, req.(*SubNet))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_AddToBlackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubNet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).AddToBlackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ab_grpc.anti_bruteforce/AddToBlackList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).AddToBlackList(ctx, req.(*SubNet))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_DelFromBlackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubNet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).DelFromBlackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ab_grpc.anti_bruteforce/DelFromBlackList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).DelFromBlackList(ctx, req.(*SubNet))
	}
	return interceptor(ctx, in, info, handler)
}

// AntiBruteforce_ServiceDesc is the grpc.ServiceDesc for AntiBruteforce service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AntiBruteforce_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ab_grpc.anti_bruteforce",
	HandlerType: (*AntiBruteforceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccessRequest",
			Handler:    _AntiBruteforce_AccessRequest_Handler,
		},
		{
			MethodName: "clearBucket",
			Handler:    _AntiBruteforce_ClearBucket_Handler,
		},
		{
			MethodName: "AddToWhileList",
			Handler:    _AntiBruteforce_AddToWhileList_Handler,
		},
		{
			MethodName: "DelFromWhileList",
			Handler:    _AntiBruteforce_DelFromWhileList_Handler,
		},
		{
			MethodName: "AddToBlackList",
			Handler:    _AntiBruteforce_AddToBlackList_Handler,
		},
		{
			MethodName: "DelFromBlackList",
			Handler:    _AntiBruteforce_DelFromBlackList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
